/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/inspection/{agencyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    agencyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Retrieve all inspections of an agency */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Inspections"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inspection/{agencyId}/{propertyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all inspections of an agency and property */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    agencyId: string;
                    propertyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get all inspections of an agency and property */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Inspections"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inspection/{agencyId}/{propertyId}/{inspectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    agencyId: string;
                    propertyId: string;
                    inspectionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get an inspection */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Inspection"];
                    };
                };
                /** @description Inspection not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inspection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Inspection"];
                };
            };
            responses: {
                /** @description Create an inspection */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Inspection"];
                };
            };
            responses: {
                /** @description Update an inspection */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        trace?: never;
    };
    "/inspection/{inspectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query: {
                    agencyId: string;
                    propertyId: string;
                };
                header?: never;
                path: {
                    inspectionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Delete an inspection */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agency/{agencyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get an agency */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    agencyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get an agency */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Agency"];
                    };
                };
                /** @description Agency not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    agencyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Delete an agency */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name: string;
                        contactMail: string;
                        contactPhone?: string;
                        address: {
                            number: string;
                            street: string;
                            city: string;
                            zipCode: string;
                            country: string;
                        };
                    };
                };
            };
            responses: {
                /** @description Agency created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Agency"];
                };
            };
            responses: {
                /** @description Update an agency */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        trace?: never;
    };
    "/property/{agencyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    agencyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get all properties of an agency */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Properties"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/property/{agencyId}/{propertyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    agencyId: string;
                    propertyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get a property */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Property"];
                    };
                };
                /** @description Property not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    agencyId: string;
                    propertyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Delete a property */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/property": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        agencyId: string;
                        address: {
                            number: string;
                            street: string;
                            city: string;
                            zipCode: string;
                            country: string;
                        };
                        owner?: {
                            firstName: string;
                            lastName: string;
                            mail?: string;
                            phoneNumber?: string;
                        };
                    };
                };
            };
            responses: {
                /** @description Create a property */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Property"];
                };
            };
            responses: {
                /** @description Update a property */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        trace?: never;
    };
    "/model/{agencyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all models of an agency */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    agencyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get all models of an agency */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Models"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model/{agencyId}/{modelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a model */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    agencyId: string;
                    modelId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get a model */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Model"];
                    };
                };
                /** @description Model not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** @description Delete a model */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    agencyId: string;
                    modelId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Delete a model */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        agencyId: string;
                        name: string;
                        rooms: {
                            name: string;
                            area?: number;
                            description?: string;
                            elements: {
                                name: string;
                                description?: string;
                                images?: string[];
                                type: string;
                            }[];
                        }[];
                    };
                };
            };
            responses: {
                /** @description Create a model */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Model"];
                };
            };
            responses: {
                /** @description Update a model */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        trace?: never;
    };
    "/room/{propertyId}/{roomId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    propertyId: string;
                    roomId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get a room */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Room"];
                    };
                };
                /** @description Room not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    propertyId: string;
                    roomId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Room deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/room/{propertyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    propertyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get all rooms of a property */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Room"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/room": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        agencyId: string;
                        propertyId: string;
                        name: string;
                        description?: string;
                        area?: number;
                    };
                };
            };
            responses: {
                /** @description Room created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Room"];
                };
            };
            responses: {
                /** @description Room updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/room-element": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        agencyId: string;
                        propertyId: string;
                        roomId: string;
                        name: string;
                        description?: string;
                        /** @enum {string} */
                        type: "FURNITURE" | "STRUCTURAL" | "ELECTRICAL" | "PLUMBING" | "VENTILATION" | "SURFACE" | "OTHER";
                    };
                };
            };
            responses: {
                /** @description Create a room element */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RoomElement"];
                };
            };
            responses: {
                /** @description Update a room element */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        trace?: never;
    };
    "/room-element/{propertyId}/{roomId}/{elementId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    propertyId: string;
                    roomId: string;
                    elementId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get a room element */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoomElement"];
                    };
                };
                /** @description Room element not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    propertyId: string;
                    roomId: string;
                    elementId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Delete a room element */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/room-element/{propertyId}/{roomId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    propertyId: string;
                    roomId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get all room elements of a room */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoomElement"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/room-element/{propertyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    propertyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get all room elements of a property */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoomElement"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Inspection: {
            agencyId: string;
            inspectionId?: string;
            propertyId: string;
            /** @enum {string} */
            status: "TO_DO" | "IN_PROGRESS" | "DONE" | "CANCELED";
            inspectorId?: string;
            date: string;
            elements?: {
                elementId: string;
                name: string;
                description?: string;
                /** @enum {string} */
                state: "GOOD" | "BAD" | "NEW" | "BROKEN" | "MISSING";
            }[];
        };
        Inspections: components["schemas"]["Inspection"][];
        Agency: {
            agencyId: string;
            name: string;
            contactMail: string;
            contactPhone?: string;
            address: {
                number: string;
                street: string;
                city: string;
                zipCode: string;
                country: string;
            };
        };
        Property: {
            propertyId: string;
            agencyId: string;
            address: {
                number: string;
                street: string;
                city: string;
                zipCode: string;
                country: string;
            };
            owner?: {
                firstName: string;
                lastName: string;
                mail?: string;
                phoneNumber?: string;
            };
        };
        Properties: components["schemas"]["Property"][];
        Model: {
            modelId: string;
            agencyId: string;
            name: string;
            rooms: {
                name: string;
                area?: number;
                description?: string;
                elements: {
                    name: string;
                    description?: string;
                    images?: string[];
                    type: string;
                }[];
            }[];
        };
        Models: components["schemas"]["Model"][];
        Room: {
            roomId: string;
            agencyId: string;
            propertyId: string;
            name: string;
            description?: string;
            area?: number;
        };
        RoomElement: {
            agencyId: string;
            propertyId: string;
            roomId: string;
            elementId: string;
            name: string;
            description?: string;
            /** @enum {string} */
            type: "FURNITURE" | "STRUCTURAL" | "ELECTRICAL" | "PLUMBING" | "VENTILATION" | "SURFACE" | "OTHER";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
