/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/inspection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Retrieve all inspections of an agency */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Inspections"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        inspectionId?: string;
                        propertyId: string;
                        /** @enum {string} */
                        status: "TO_DO" | "IN_PROGRESS" | "DONE" | "CANCELED";
                        inspectorId?: string;
                        date: string;
                        rooms?: {
                            name: string;
                            description?: string;
                            elements: {
                                name: string;
                                description?: string;
                                images?: string[];
                                /** @enum {string} */
                                state: "GOOD" | "BAD" | "NEW" | "BROKEN";
                            }[];
                        }[];
                    };
                };
            };
            responses: {
                /** @description Create an inspection */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        inspectionId?: string;
                        propertyId: string;
                        /** @enum {string} */
                        status: "TO_DO" | "IN_PROGRESS" | "DONE" | "CANCELED";
                        inspectorId?: string;
                        date: string;
                        rooms?: {
                            name: string;
                            description?: string;
                            elements: {
                                name: string;
                                description?: string;
                                images?: string[];
                                /** @enum {string} */
                                state: "GOOD" | "BAD" | "NEW" | "BROKEN";
                            }[];
                        }[];
                    };
                };
            };
            responses: {
                /** @description Update an inspection */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        trace?: never;
    };
    "/inspection/{propertyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all inspections of an agency and property */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    propertyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get all inspections of an agency and property */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Inspections"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inspection/{propertyId}/{inspectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    propertyId: string;
                    inspectionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get an inspection */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Inspection"];
                    };
                };
                /** @description Inspection not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inspection/{inspectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query: {
                    propertyId: string;
                };
                header?: never;
                path: {
                    inspectionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Delete an inspection */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get an agency */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get an agency */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Agency"];
                    };
                };
                /** @description Agency not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name: string;
                        contactMail: string;
                        contactPhone?: string;
                        address: {
                            number: string;
                            street: string;
                            city: string;
                            zipCode: string;
                            country: string;
                        };
                    };
                };
            };
            responses: {
                /** @description Update an agency */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        trace?: never;
    };
    "/agency/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get an agency */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get all agencies of user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Agency"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/property": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get all properties of an agency */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Properties"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        address: {
                            number: string;
                            street: string;
                            city: string;
                            zipCode: string;
                            country: string;
                        };
                        owner?: {
                            firstName: string;
                            lastName: string;
                            mail?: string;
                            phoneNumber?: string;
                        };
                        rooms: {
                            name: string;
                            area?: number;
                            description?: string;
                            elements: {
                                name: string;
                                description?: string;
                                images?: string[];
                                type: string;
                            }[];
                        }[];
                    };
                };
            };
            responses: {
                /** @description Create a property */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        propertyId: string;
                        address: {
                            number: string;
                            street: string;
                            city: string;
                            zipCode: string;
                            country: string;
                        };
                        owner?: {
                            firstName: string;
                            lastName: string;
                            mail?: string;
                            phoneNumber?: string;
                        };
                        rooms: {
                            name: string;
                            area?: number;
                            description?: string;
                            elements: {
                                name: string;
                                description?: string;
                                images?: string[];
                                type: string;
                            }[];
                        }[];
                    };
                };
            };
            responses: {
                /** @description Update a property */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        trace?: never;
    };
    "/property/{propertyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    propertyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get a property */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Property"];
                    };
                };
                /** @description Property not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    propertyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Delete a property */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all models of an agency */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get all models of an agency */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Models"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name: string;
                        rooms: {
                            name: string;
                            area?: number;
                            description?: string;
                            elements: {
                                name: string;
                                description?: string;
                                images?: string[];
                                type: string;
                            }[];
                        }[];
                    };
                };
            };
            responses: {
                /** @description Create a model */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        modelId: string;
                        name: string;
                        rooms: {
                            name: string;
                            area?: number;
                            description?: string;
                            elements: {
                                name: string;
                                description?: string;
                                images?: string[];
                                type: string;
                            }[];
                        }[];
                    };
                };
            };
            responses: {
                /** @description Update a model */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        trace?: never;
    };
    "/model/{modelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a model */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    modelId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get a model */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Model"];
                    };
                };
                /** @description Model not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** @description Delete a model */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    modelId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Delete a model */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Inspection: {
            agencyId: string;
            inspectionId?: string;
            propertyId: string;
            /** @enum {string} */
            status: "TO_DO" | "IN_PROGRESS" | "DONE" | "CANCELED";
            inspectorId?: string;
            date: string;
            rooms?: {
                name: string;
                description?: string;
                elements: {
                    name: string;
                    description?: string;
                    images?: string[];
                    /** @enum {string} */
                    state: "GOOD" | "BAD" | "NEW" | "BROKEN";
                }[];
            }[];
        };
        Inspections: components["schemas"]["Inspection"][];
        Agency: {
            agencyId: string;
            name: string;
            contactMail: string;
            contactPhone?: string;
            address: {
                number: string;
                street: string;
                city: string;
                zipCode: string;
                country: string;
            };
        };
        Property: {
            propertyId: string;
            agencyId: string;
            address: {
                number: string;
                street: string;
                city: string;
                zipCode: string;
                country: string;
            };
            owner?: {
                firstName: string;
                lastName: string;
                mail?: string;
                phoneNumber?: string;
            };
            rooms: {
                name: string;
                area?: number;
                description?: string;
                elements: {
                    name: string;
                    description?: string;
                    images?: string[];
                    type: string;
                }[];
            }[];
        };
        Properties: components["schemas"]["Property"][];
        Model: {
            modelId: string;
            agencyId: string;
            name: string;
            rooms: {
                name: string;
                area?: number;
                description?: string;
                elements: {
                    name: string;
                    description?: string;
                    images?: string[];
                    type: string;
                }[];
            }[];
        };
        Models: components["schemas"]["Model"][];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
