"use client";

import { useState } from "react";
import { Button } from "../ui/button";
import { Input } from "../ui/input";
import { Label } from "../ui/label";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "../ui/card";
import { PlusIcon } from "lucide-react";
import { Inspection, Room, RoomElement } from "@/lib/dashboard-mgt-bff";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "../ui/select";
import InspectionElementEditor from "./element-editor";

type InspectionElement = NonNullable<Inspection["elements"]>[number];

interface InspectionRoomsManagerProps {
  propertyRooms: Room[];
  propertyRoomElements: RoomElement[];
  inspectionElements: Inspection["elements"];
  onChange: (elements: Inspection["elements"]) => void;
}

export default function InspectionRoomsManager({
  propertyRooms,
  propertyRoomElements,
  inspectionElements,
  onChange,
}: InspectionRoomsManagerProps) {
  const [selectedRoomIndex, setSelectedRoomIndex] = useState<number | null>(
    propertyRooms.length > 0 ? 0 : null
  );
  const [newElementName, setNewElementName] = useState("");

  // Get current property room
  const currentPropertyRoom =
    selectedRoomIndex !== null ? propertyRooms[selectedRoomIndex] : null;

  // Get room elements for current room
  const currentRoomElements = currentPropertyRoom
    ? propertyRoomElements.filter(
        (e) => e.roomId === currentPropertyRoom.roomId
      )
    : [];

  // Get inspection elements for current room (by matching elementId)
  const getInspectionElementsForRoom = (
    roomId: string
  ): InspectionElement[] => {
    if (!inspectionElements) return [];
    const roomElementIds = propertyRoomElements
      .filter((e) => e.roomId === roomId)
      .map((e) => e.elementId);
    return inspectionElements.filter((e) =>
      roomElementIds.includes(e.elementId)
    );
  };

  // Get inspection-only elements (not matching any property elementId)
  const getInspectionOnlyElements = (): InspectionElement[] => {
    if (!inspectionElements) return [];
    const propertyElementIds = new Set(
      propertyRoomElements.map((e) => e.elementId)
    );
    return inspectionElements.filter(
      (e) => !propertyElementIds.has(e.elementId)
    );
  };

  // Find or create inspection element for a property room element
  const getInspectionElement = (
    roomElement: RoomElement
  ): InspectionElement | null => {
    if (!inspectionElements) return null;
    return (
      inspectionElements.find((e) => e.elementId === roomElement.elementId) ||
      null
    );
  };

  // Add property room element to inspection
  const addPropertyElementToInspection = (roomElement: RoomElement) => {
    if (!inspectionElements) {
      const newElement: InspectionElement = {
        elementId: roomElement.elementId,
        name: roomElement.name,
        description: roomElement.description || "",
        state: "NEW",
      };
      onChange([newElement]);
      return;
    }
    const existing = inspectionElements.find(
      (e) => e.elementId === roomElement.elementId
    );
    if (existing) return; // Already added

    const newElement: InspectionElement = {
      elementId: roomElement.elementId,
      name: roomElement.name,
      description: roomElement.description || "",
      state: "NEW",
    };
    onChange([...inspectionElements, newElement]);
  };

  // Update inspection element
  const updateInspectionElement = (
    elementId: string,
    updates: Partial<InspectionElement>
  ) => {
    if (!inspectionElements) return;
    const updated = inspectionElements.map((e) =>
      e.elementId === elementId ? { ...e, ...updates } : e
    );
    onChange(updated);
  };

  // Remove inspection element
  const removeInspectionElement = (elementId: string) => {
    if (!inspectionElements) return;
    const updated = inspectionElements.filter((e) => e.elementId !== elementId);
    onChange(updated);
  };

  // Add new custom element (inspection-only)
  const addNewElement = () => {
    if (!newElementName.trim() || !currentPropertyRoom) return;

    // Check if element with same name already exists
    const elementExists = inspectionElements?.some(
      (e) => e.name === newElementName.trim()
    );
    if (elementExists) {
      setNewElementName("");
      return;
    }

    // Create new element without elementId (will be generated by backend)
    const newElement: InspectionElement = {
      elementId: `temp_${Date.now()}`, // Temporary ID, will be replaced by backend
      name: newElementName.trim(),
      description: "",
      state: "NEW",
    };
    onChange([...(inspectionElements || []), newElement]);
    setNewElementName("");
  };

  if (propertyRooms.length === 0) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Inspection Elements</CardTitle>
          <CardDescription>No rooms available in this property</CardDescription>
        </CardHeader>
      </Card>
    );
  }

  const currentInspectionElements = currentPropertyRoom
    ? getInspectionElementsForRoom(currentPropertyRoom.roomId)
    : [];
  const inspectionOnlyElements = getInspectionOnlyElements();

  // Use horizontal buttons for few rooms, dropdown for many
  const useButtons = propertyRooms.length <= 5;

  return (
    <div className="flex flex-col gap-6 max-w-4xl w-full">
      <Card>
        <CardHeader>
          <CardTitle>Inspection Elements</CardTitle>
          <CardDescription>
            Select property elements to inspect or add custom elements. Add new
            elements if needed.
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col gap-6">
          {useButtons ? (
            <div className="flex flex-col gap-4">
              <div className="flex flex-wrap gap-2">
                {propertyRooms.map((room, index) => (
                  <Button
                    key={room.roomId}
                    variant={
                      selectedRoomIndex === index ? "default" : "outline"
                    }
                    onClick={() => setSelectedRoomIndex(index)}
                    size="sm"
                  >
                    {room.name || `Room ${index + 1}`}
                  </Button>
                ))}
              </div>
              {currentPropertyRoom && (
                <RoomContent
                  propertyRoom={currentPropertyRoom}
                  roomElements={currentRoomElements}
                  inspectionElements={currentInspectionElements}
                  onAddPropertyElement={addPropertyElementToInspection}
                  onUpdateElement={updateInspectionElement}
                  onRemoveElement={removeInspectionElement}
                  onAddNewElement={addNewElement}
                  newElementName={newElementName}
                  setNewElementName={setNewElementName}
                />
              )}
            </div>
          ) : (
            <div className="flex flex-col gap-4">
              <div>
                <Label>Select Room</Label>
                <Select
                  value={selectedRoomIndex?.toString() || ""}
                  onValueChange={(value) =>
                    setSelectedRoomIndex(parseInt(value))
                  }
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select a room" />
                  </SelectTrigger>
                  <SelectContent>
                    {propertyRooms.map((room, index) => (
                      <SelectItem key={room.roomId} value={index.toString()}>
                        {room.name || `Room ${index + 1}`}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              {currentPropertyRoom && (
                <RoomContent
                  propertyRoom={currentPropertyRoom}
                  roomElements={currentRoomElements}
                  inspectionElements={currentInspectionElements}
                  onAddPropertyElement={addPropertyElementToInspection}
                  onUpdateElement={updateInspectionElement}
                  onRemoveElement={removeInspectionElement}
                  onAddNewElement={addNewElement}
                  newElementName={newElementName}
                  setNewElementName={setNewElementName}
                />
              )}
            </div>
          )}

          {/* Inspection-Only Elements (not from property) */}
          {inspectionOnlyElements.length > 0 && (
            <div className="flex flex-col gap-4 pt-4 border-t">
              <Label className="text-base font-semibold">
                Additional Elements
              </Label>
              <div className="flex flex-col gap-4">
                {inspectionOnlyElements.map((element) => (
                  <InspectionElementEditor
                    key={element.elementId}
                    element={element}
                    propertyRoomElement={null}
                    elementKey={`additional-${element.elementId}`}
                    onUpdate={(updates) =>
                      updateInspectionElement(element.elementId, updates)
                    }
                    onRemove={() => removeInspectionElement(element.elementId)}
                    isAdditional={true}
                  />
                ))}
              </div>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

interface RoomContentProps {
  propertyRoom: Room;
  roomElements: RoomElement[];
  inspectionElements: InspectionElement[];
  onAddPropertyElement: (roomElement: RoomElement) => void;
  onUpdateElement: (
    elementId: string,
    updates: Partial<InspectionElement>
  ) => void;
  onRemoveElement: (elementId: string) => void;
  onAddNewElement: () => void;
  newElementName: string;
  setNewElementName: (name: string) => void;
}

function RoomContent({
  propertyRoom,
  roomElements,
  inspectionElements,
  onAddPropertyElement,
  onUpdateElement,
  onRemoveElement,
  onAddNewElement,
  newElementName,
  setNewElementName,
}: RoomContentProps) {
  // Get elements that are in property but not yet in inspection
  const availableElements = roomElements.filter(
    (re) => !inspectionElements.some((ie) => ie.elementId === re.elementId)
  );

  // Get elements that are in inspection
  const inspectedElements = roomElements
    .filter((re) =>
      inspectionElements.some((ie) => ie.elementId === re.elementId)
    )
    .map((re) => {
      const inspectionElement = inspectionElements.find(
        (ie) => ie.elementId === re.elementId
      )!;
      return { roomElement: re, inspectionElement };
    });

  return (
    <div className="flex flex-col gap-6">
      {/* Room Description */}
      {propertyRoom.description && (
        <div className="text-sm text-muted-foreground">
          {propertyRoom.description}
        </div>
      )}

      {/* Available Property Elements - Can be added */}
      {availableElements.length > 0 && (
        <div className="flex flex-col gap-4">
          <Label className="text-base font-semibold">
            Available Property Elements
          </Label>
          <div className="flex flex-col gap-2">
            {availableElements.map((roomElement) => (
              <Card
                key={roomElement.elementId}
                className="border-2 border-dashed"
              >
                <CardContent className="p-4 flex items-center justify-between">
                  <div>
                    <p className="font-medium">{roomElement.name}</p>
                    {roomElement.description && (
                      <p className="text-sm text-muted-foreground">
                        {roomElement.description}
                      </p>
                    )}
                  </div>
                  <Button
                    onClick={() => onAddPropertyElement(roomElement)}
                    variant="outline"
                    size="sm"
                  >
                    <PlusIcon className="w-4 h-4 mr-2" />
                    Add to Inspection
                  </Button>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      )}

      {/* Inspected Elements - Already in inspection */}
      {inspectedElements.length > 0 && (
        <div className="flex flex-col gap-4">
          <Label className="text-base font-semibold">Inspected Elements</Label>
          <div className="flex flex-col gap-4">
            {inspectedElements.map(({ roomElement, inspectionElement }) => (
              <InspectionElementEditor
                key={inspectionElement.elementId}
                element={inspectionElement}
                propertyRoomElement={roomElement}
                elementKey={`property-${inspectionElement.elementId}`}
                onUpdate={(updates) =>
                  onUpdateElement(inspectionElement.elementId, updates)
                }
              />
            ))}
          </div>
        </div>
      )}

      {/* Add New Custom Element Section */}
      <div className="flex flex-col gap-3">
        <Label>Add New Custom Element</Label>
        <div className="flex gap-2">
          <Input
            type="text"
            value={newElementName}
            onChange={(e) => setNewElementName(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && newElementName.trim()) {
                onAddNewElement();
              }
            }}
            placeholder="Element name"
            className="flex-1"
          />
          <Button
            onClick={onAddNewElement}
            disabled={!newElementName.trim()}
            variant="outline"
          >
            <PlusIcon className="w-4 h-4 mr-2" />
            Add
          </Button>
        </div>
      </div>
    </div>
  );
}
